### ISSUE TITLE
Update Metrics to latest specification.

### ISSUE THREAD

**Issue by jsuereth** [open-telemetry/opentelemetry-java#3518]
Here's the task list for taking the prototyped ideas in #3333 and piecemeal submitting them into main branch.

- [x] Update data model 
   - [x] Attributes #3352
   - [x] Exemplars #3353
- [x] Update API #3423
- [x] Update SDK
  - [x] Views
    - [x] Per-metric-storage vs. instrument #3455
    - [x] Select by InstrumentationLibraryInfo #3491
    - [X] Enable metric renaming / redescription #3510
    - [x] Do not crash (by default) when a metric name conflict is detected, instead issue an error. #3541
    - [x]  Allow multiple views per-instrument as long as there are no name conflicts #3541
    - [X] Improve error message + provenance of metric-name clashes. #3808
    - [x] Move aggregator package to internal, only expose necessary public interfaces #3557
    - [x] Rework LabelsProcessor, allow Baggage attribute additions. #3562
    - [x] Allow wildcard matching (#3642)
    - [x] Remove AggregationTemporality from aggregator config (spec update)
  - [x] Exemplars
    - [x] Implement ExemplarFilter + wire into correct paths #3591
    - [x] Implement ExemplarReservoir + wire into aggregator #3583
    - [x] Implement simple + histogram reservoirs #3592
    - [x] Implement mechanism to use aggregation configuration to instantiate exemplar reservoirs #3599
  - [x] Multi-Exporter
    - [x] Initial specification implementation #3578
    - [x] allow multiple reader "within interval" to avoid re-collecting synchronous metrics. #3689
    
    
## Cleanups

- [x] Exemplar data class names #3688
- [ ] Multi-registration of instrument errors #3809
- [ ] PeriodicMetricReader environment variables #3746
- [ ] Environment variable configuration for OTLP exporter aggregation temporality

## (Optional) Follow-ons
- [ ] Optimise MetricDescriptor exports #3534
- [ ] Optimise Async instruments to only collect once per-collection vs. once-per-metric-per-collection.
- [ ] pre-allocate delta storage and limit its size. That should be hidden in this class and would be per-metric.
- [ ] join multiple MetricExporters into a single MetricReader if they all use periodic metric reader.

**Comment by jamesmoessis** [comment]
Exponential histogram coming later I suppose?

**Comment by jsuereth** [comment]
Yeah, this is not a complete list.   As things get better specified, they'll be added.


For exponential histograms, I'd highly recommend doing a parallel experiment right now.  While I expect the Aggregator package to undergo some refactorings (and hopefully simplifications) you should be able to prototype an exponential hsitogram today.

I opened a bug around that here: https://github.com/open-telemetry/opentelemetry-java/issues/3550

**Comment by breedx-splk** [comment]
related to #3724

**Comment by jack-berg** [comment]
An additional problem I've noticed is that you can use the metric API / SDK to produce metrics streams that violate their monotonic properties.

For example, take the following async counter:
```
AtomicLong count = new AtomicLong(100);
    meter
        .counterBuilder("async-counter")
        .buildWithCallback(
            measurement ->
                measurement.observe(count.decrementAndGet()));
```
For both cumulative and metric exporters, this will product monotonic sums that violate their monotonicity. In the delta case, the values will be negative, which is a violation. In the cumulative case, the values will be decreases, which is a violation. 

The same thing is true a a sync counter:
```
    AtomicLong count = new AtomicLong(100);

    LongCounter counter = meter.counterBuilder("sync-counter").build();
    counter.add(count.decrementAndGet());
    // .. await export
    counter.add(count.decrementAndGet());
    // .. await export
    counter.add(count.decrementAndGet());
```

The question is what should the SDK do in these cases where the recorded value violates the assumptions of the instrument.

**Comment by jsuereth** [comment]
I'm not sure I understand the sync counter bit?   The counter should be adding all those non-negative measurments together.


For the *first* problem, we assume good-faith on the callback functions, and we should carefully document expectations on those. (Similar to requirements on these about good thread-management, blocking calls, etc.).  I'm not convinced the SDK needs to do something in its production pathway, but I do think a testing-SDK that highlights issues like this should issue exceptions.

**Comment by jack-berg** [comment]
> I'm not sure I understand the sync counter bit? The counter should be adding all those non-negative measurments together.

Right right, something got crossed in my brain. 

>  I'm not convinced the SDK needs to do something in its production pathway,

I'm not sure I do either. At least not without a convincing argument of what the SDK should do from an export perspective when these scenarios occur. 

It's worth noting that counters (`SdkLongCounter`, `SdkDoubleCounter`) throw exceptions if you try to report a negative number. Maybe we could do the same with async instruments?

**Comment by jsuereth** [comment]
> It's worth noting that counters (SdkLongCounter, SdkDoubleCounter) throw exceptions if you try to report a negative number. Maybe we could do the same with async instruments?

Just making sure it's non-negative?  Yeah.  I do think it's worth having a "test" or "verify" mode for the sdk where more of these assertions come into play for folks writing instrumentation, so it's not just a  "log and ask end-users to fix" thing (although we also shouldn't punish end-users if library-instrumentation is bad, we SHOULD log and ask-to-fix if they see it in production).

For the purposes of tracking here, it should be added.  Do you have edit access to update TOOOs/link other issues?  If so, please feel free to update any "stable-release" blocking things you think we need to do.  If not, let me know what you want added here and I'll make sure this represents our "known TODOs prior to stable" and check with @anuraaga and @jkwatson for their list as well.

**Comment by jkwatson** [comment]
> For the purposes of tracking here, it should be added. Do you have edit access to update TOOOs/link other issues? If so, please feel free to update any "stable-release" blocking things you think we need to do. If not, let me know what you want added here and I'll make sure this represents our "known TODOs prior to stable" and check with @anuraaga and @jkwatson for their list as well.

Thou shalt create an issue if you want it to be remembered. ;)

**Comment by jsuereth** [comment]
Moving remaining tracking items to: https://github.com/open-telemetry/opentelemetry-java/projects/3

**Comment by jack-berg** [comment]
Created a new issue from my comment [here](https://github.com/open-telemetry/opentelemetry-java/issues/3861).
