### ISSUE TITLE
Make exponential histograms more available

### ISSUE THREAD

**Issue by jack-berg** [open-telemetry/opentelemetry-java#4540]
We have an exponential histogram implementation but because exponential histograms aren't yet stable in the metrics spec, the implementation is obscure / difficult to use. This issue is tracking steps to make histograms easier to use, even while they remain experimental. If they're easier to use, we can get feedback that may help stabilize the specification.

- [x] Align exponential histogram implementation with specification #4536 
- [ ] MetricReader can influence default aggregation by instrument kind #4472
- [ ] MetricExporter can influence default aggregation of PeriodicMetricReader
- [ ] Add autoconfigure option for using exponential histogram aggregation as default aggregation for otlp metric exporters. Implementation of spec [PR #2619](https://github.com/open-telemetry/opentelemetry-specification/pull/2619).
