### ISSUE TITLE
Implement log appender / event api

### ISSUE THREAD

**Issue by jack-berg** [open-telemetry/opentelemetry-java#4714]
The spec is going to soon have a [log appender / event API](https://github.com/open-telemetry/opentelemetry-specification/pull/2676), in addition to the existing SDK.

To implement we need:
- [x] Rename classes for alignment. We have `LogEmitterProvider` and `LogEmitter` right now, we're going to need `LoggerProvider` and `Logger`. The rename is going to sting quite a bit because stable artifacts like `OpenTelemetrySdk` have references to the old names. We justified this because although `OpenTelemetrySdk` is stable, you need to take a dependency on the log SDK in order to use the log portions of the API. We'll need to make one time exception rules for jApiCmp to pass. #4721
- [x] Break out `:api:logs` module, including interfaces like `LoggerProvider`, `Logger`, `LogRecordBuilder`, etc. #4764
- [x] Add `GlobalLoggerProvider` akin to the old `GlobalMeterProvider`, which will hold global reference while until log stability is reached and it can merge with `GlobalOpenTelemetry`. #4764
- [ ] Extend API for events. `Logger` should have a `logRecordBuilder()` for use by log appenders, and `eventBuilder(String name)` for events. 
- [x] Rename `LogProcessor`, `*LogProcessor` to `LogRecordProcessor`, `*LogRecordProcessor`. #4772 
- [x] Rename `LogExporter`, `*LogExporter` to `LogRecordExporter`, `*LogRecordExporter`. #4773 
- [x] Rename `LogData` to `LogRecordData`. #4774

When this is complete the instrumentation repo will be able to delete [instrumentation-appender-api-internal](https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/instrumentation-appender-api-internal) and [instrumentation-appender-sdk-internal](https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/instrumentation-appender-sdk-internal) 🎉.
